FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build

WORKDIR /src

# Phase #1, copy solution + csproj and restore as distinct layers  ----
COPY *.sln .
COPY Client/*.csproj ./Client/
COPY Infrastructure/*.csproj ./Infrastructure/
COPY PaymentAPI/*.csproj ./PaymentAPI/
COPY IdentityService/*.csproj ./IdentityService/
#COPY IdentityServer.EntityFramework/*.csproj ./IdentityServer.EntityFramework/
#COPY IdentityService.Configuration/*.csproj ./IdentityService.Configuration/


RUN dotnet restore --runtime alpine-x64


# Phase #2, copy everything and build app ------------------------------
COPY . .

WORKDIR "/src/IdentityService"

RUN dotnet publish IdentityService.csproj -c Release -o /app/IdentityService \
    --no-restore \    
    --runtime alpine-x64 

# Phase #3, Build final image ------------------------------------------
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS release

#Set by the build-server
ARG buildnumber="unknown"

COPY --from=build /app/IdentityService .

EXPOSE 80
EXPOSE 443

WORKDIR /

# Enable globalization support that is lacking in the alphine image
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV TZ=Europe/Stockholm
RUN apk add --no-cache tzdata icu-libs


ENTRYPOINT ["dotnet", "IdentityService.dll"]

RUN echo "buildversion=$buildversion\n"
RUN echo "buildnumber=$buildnumber\n"